upcloud/resource_upcloud_server.go
Use SDK provided const strings in server resource.
=> Use const strings from the SDK

README.md
Updated the README file to have a bit more structure.
=> Updated the README to have a bit more structure

.travis.yml, scripts/gogetcookie.sh
=> Add Travis tests

.gitignore, .gitlab-ci.yml, .goreleaser.yml, .travis.yml, go.sum, release/Dockerfile, release/entrypoint.sh
* add goreleaser config
* add GitLab CI file
* add necessary build environment setup files to release/
=> Implement a release CI process

upcloud/resource_upcloud_server.go
- clean up resourceUpCloudServerUpdate
- also handle hostname update
=> WIP: Fix/server update

CHANGELOG.md, internal/globals.go, scripts/globals.sh, upcloud/provider.go
First try at adding header in provider.
=> feat: add user-agent to header

README.md
=> Highlight Terraform code in README

.github/workflows/terraform.yml
@Darep ...and resolve acceptance test failure in PR-s
From https://github.com/UpCloudLtd/terraform-provider-upcloud/pull/126#issuecomment-769633817
=> Properly name CI jobs

CHANGELOG.md, examples/sdn_private_network.tf
=> Add example for SDN private network & attaching it to a server

CHANGELOG.md, internal/server/server.go, upcloud/resource_upcloud_server.go, upcloud/resource_upcloud_storage.go, website/docs/r/upcloud_server.html.markdown
add support for explicitly selecting host (for private cloud customers)
(also fixes server not starting when updating storages, was referring to storage id previously)
=> feat(server): add host field

upcloud/resource_upcloud_firewall_rules_test.go
=> chore(test): fix firewall test

upcloud/resource_upcloud_server.go
Some attributes don't need a restart to be updated
=> fix(server): prevent some attribute update from restarting

upcloud/resource_upcloud_storage.go
=> fix(storage): check size before cloning a device

upcloud/resource_upcloud_server.go
=> fix(server/login): make login user optional

.github/workflows/release.yml, .goreleaser.yml
[follow official doc](https://learn.hashicorp.com/tutorials/terraform/provider-release-publish?utm_offer=ARTICLE_PAGE)
=> chore(ci): update release workflow

.goreleaser.yml
Revert changes done for `goreleaser.yml` that affects gitlab CI #155 
=> chore(ci): fix gitlab ci

.goreleaser.yml, release/Dockerfile
=> fix(ci): misc gitlab CI

GNUmakefile, internal/config/config.go, upcloud/provider.go
=> fix(client): fix user-agent value

CHANGELOG.md
=> Release v2.1.1

CHANGELOG.md, upcloud/resource_upcloud_server.go, upcloud/resource_upcloud_server_test.go
Validate hostname field to catch errors in plan phase.
=> feat(server): validate server hostname

CHANGELOG.md, upcloud/resource_upcloud_server.go, upcloud/resource_upcloud_server_test.go
Validate field values before executing API commands.
=> feat(server): validate plan and zone

CHANGELOG.md
Add changes made on #209 to changelog.
=> Add object storage fix to changelog

CHANGELOG.md, upcloud/resource_upcloud_storage.go
Fix missing backup_rule when importing storage resource.
=> fix(storage): fix missing backup_rule

GNUmakefile, examples/execute_commands.tf, examples/floating_ip_address.tf, examples/object_storage.tf, examples/sdn_private_network.tf, examples/server.tf
Reformat config examples using `terraform fmt`
=> chore(examples): reformat config examples

CHANGELOG.md, go.mod, go.sum, internal/service/database/database_common.go
- require that both `maintenance_window_time` and `maintenance_window_dow` are set when defining maintenance window
- fix `maintenance_window_time` format
=> fix(dbaas): maintenance window properties

CHANGELOG.md
I've realised I forgot to update changelog in the last two PRs I've merged :)
=> fix: add missing changelog entries

CHANGELOG.md, go.mod, internal/service/database/database.go, internal/service/database/logical_database.go, internal/service/database/user.go, internal/service/loadbalancer/backend.go, internal/service/loadbalancer/backend_member.go, internal/service/loadbalancer/dynamic_certificate_bundle.go, internal/service/loadbalancer/frontend.go, internal/service/loadbalancer/frontend_rule.go, internal/service/loadbalancer/frontend_tls_config.go, internal/service/loadbalancer/loadbalancer.go, internal/service/loadbalancer/manual_certificate_bundle.go, internal/service/loadbalancer/resolver.go, internal/service/server/server.go, internal/service/storage/storage.go, internal/utils/server.go, upcloud/config.go
Replace Go's logger with `tflog` package.
=> chore(logging): replace log with tflog

internal/service/kubernetes/data_sources.go, internal/service/kubernetes/kubernetes.go
Adds a note about all UKS features being in alpha phase.
=> docs(kubernetes): add alpha note to all uks resources

docs/resources/server.md, internal/service/server/server.go
This PR adds a short example on how to list available server plans.
=> feat(server): list server plans

CHANGELOG.md, docs/resources/managed_database_mysql.md, docs/resources/managed_database_postgresql.md, docs/resources/managed_database_redis.md, internal/service/database/database_common.go, internal/service/database/postgresql.go, internal/service/database/redis.go
Removed properties:
- shared: `additional_backup_regions`
- pg: `enable_ipv6`
- redis: `recovery_basebackup_name`
=> fix(dbaas): remove unsupported properties

CHANGELOG.md, upcloud/provider.go, upcloud/resource_upcloud_objectstorage_test.go
Related PR: https://github.com/UpCloudLtd/terraform-provider-upcloud/pull/441
=>  feat(provider): http request timeout

CHANGELOG.md
=> chore: prepare v3.3.0 release

CHANGELOG.md
=> chore: prepare v3.3.1 release

DEVELOPING.md, release/Dockerfile
Just updating go version in dockerfile, we forgot about it during last go version update
=> fix: update go version in dockerfile

release/Dockerfile
We need to also update goreleaser in dockerfile
=> fix: update goreleaser

CHANGELOG.md, internal/service/database/logical_database.go
Fixes how we handle the not found errors for logical databases.
=> fix(database): handling not found errors in logical database

CHANGELOG.md, docs/resources/kubernetes_cluster.md, docs/resources/kubernetes_node_group.md, go.mod, go.sum, internal/service/kubernetes/kubernetes.go, internal/service/kubernetes/node_group.go, internal/service/kubernetes/utils.go, upcloud/resource_upcloud_kubernetes_test.go, upcloud/testdata/upcloud_kubernetes/kubernetes_labels_s1.tf, upcloud/testdata/upcloud_kubernetes/kubernetes_s1.tf, upcloud/testdata/upcloud_kubernetes/kubernetes_s2.tf
This adds support for node group custom plans and storage encryption.
=> feat(kubernetes): custom plans and storage encryption

CHANGELOG.md, internal/service/database/database.go
This seems to fix bug described in #541
=> fix(dbaas): filter nested properties similarly than top level properties

CHANGELOG.md
=> chore: prepare release v5.7.0

CHANGELOG.md, go.mod, go.sum, internal/service/kubernetes/node_group.go, internal/service/kubernetes/utils.go
Allow disabling cluster level storage encryption in node group.
=> feat(kubernetes): update node group storage encryption validator

CHANGELOG.md
=> chore: prepare release v5.8.0

CHANGELOG.md, internal/service/managedobjectstorage/managed_object_storage.go
=> chore: prepare release v5.9.1

CHANGELOG.md
=> chore: prepare release v5.10.0

CHANGELOG.md, examples/data-sources/upcloud_load_balancer_dns_challenge_domain/data-source.tf, examples/resources/upcloud_managed_object_storage_custom_domain/resource.tf, go.mod, go.sum, internal/service/loadbalancer/dns_challenge_domain_data_source.go, internal/service/managedobjectstorage/custom_domain.go, internal/service/managedobjectstorage/policy.go, subcategories.json, upcloud/provider.go, upcloud/resource_upcloud_managed_object_storage_test.go, upcloud/testdata/upcloud_managed_object_storage/managed_object_storage_custom_domain_s1.tf, upcloud/testdata/upcloud_managed_object_storage/managed_object_storage_custom_domain_s2.tf, upcloud/testdata/upcloud_managed_object_storage/managed_object_storage_custom_domain_s3.tf
=> feat(objsto): add resource for managing custom domains

CHANGELOG.md, internal/service/storage/storage.go, upcloud/resource_upcloud_storage_test.go
See #630 for the bug description.
=> fix(storage): set `Content-Type` based on file extension

CHANGELOG.md, internal/service/loadbalancer/backend.go
Related to https://github.com/UpCloudLtd/terraform-provider-upcloud/issues/647
=> fix(loadbalancer): state upgrade due to previous schema version bump

CHANGELOG.md, go.mod, go.sum, internal/service/loadbalancer/frontend_rule.go, upcloud/resource_upcloud_loadbalancer_test.go, upcloud/testdata/upcloud_loadbalancer/loadbalancer_minimal.tf, upcloud/testdata/upcloud_loadbalancer/loadbalancer_rules_e2e.tf, upcloud/testdata/upcloud_loadbalancer/loadbalancer_s3.tf
=> feat(loadbalancer): add `matching_condition` field to frontend rule

CHANGELOG.md, DEVELOPING.md, go.mod, go.sum, upcloud/sdkv2_provider.go
Depends on https://github.com/UpCloudLtd/upcloud-go-api/pull/325
=> feat: log UpCloud API requests and responses

CHANGELOG.md, examples/resources/upcloud_managed_object_storage_bucket/resource.tf, internal/service/managedobjectstorage/bucket.go, internal/service/managedobjectstorage/custom_domain.go, internal/service/managedobjectstorage/utils.go, subcategories.json, upcloud/provider.go, upcloud/resource_upcloud_managed_object_storage_test.go, upcloud/testdata/upcloud_managed_object_storage/managed_object_storage_s1.tf
=> feat(objsto): add bucket resource

upcloud/provider.go
Add details to authentication error if checkLogin() fails.
=> chore(provider): improve auth error logging on provider configuration

CHANGELOG.md
=> chore: prepare release v5.20.2

CHANGELOG.md
=> chore: prepare release v5.20.3

.github/workflows/terraform.yml
=> ci: add cleanup job to acceptance tests workflow

.golangci.yml, go.mod, go.sum, internal/config/config.go, upcloud/provider.go, upcloud/sdkv2_provider.go
=> feat: add support for reading credentials from keyring

CHANGELOG.md
=> chore: prepare release v5.23.2

CHANGELOG.md
=> chore: prepare release v5.23.3
