UpCloudLtd/terraform-provider-upcloud

- .dockerignore
- Dockerfile
- main.go
Add Dockerfile for running provider inside a container. Will be useful for CI purposes and testing.
Uses multi-stage builds on Alpine 3.6. Docker CE >=17.05 is required.
> Add Docker support

- upcloud/resource_upcloud_server.go
Previously instance `user_data` was not passed on properly.
Now that this is fixed `user_data` scripts can be used by templating them in Terraform.
```
data "template_file" "bootstrap" {
template = "${file("${path.module}/user_data.sh")}"
}
resource "upcloud_server" "test" {
...
user_data = "${data.template_file.bootstrap.rendered}"
}
```
> Fix typo in user_data parameter handling

- examples/01_server.tf
- examples/README.md
- upcloud/resource_upcloud_server.go
It is now possible to define login credentials by using a `login` block inside server config. This configuration should at least define a username and a SSH key.
Also, it is possible to let UpCloud generate a password for you and deliver it to you through customizable method `{"none", "email", "sms"}``. However, in terms of automation this is typically not feasible so by default a password is not generated nor delivered.
Example generates user `tf` and associates a SSH key with it.
```
resource "upcloud_server" "test2" {
...
login {
user = "tf"
keys = [
"ssh-rsa ..."
]
}
}
```
Updated docs and example configs.
Fixes #2.
> Implement login definitions for servers

- README.md
- examples/README.md
Simplified the installation instructions of the go code and added a step to symlink the provider into a folder where Terraform will find it when running `terraform init`.
This fixes #16.
> Adjusted the installation instructions and example instructions

- examples/01_server.tf
- examples/README.md
Update example configuration to set state output for server IPv4 address. Also, change example template image from CentOS to Ubuntu as old CentOS minor versions are being pruned while newer version are being rolled out.
Relates to #18.
> Output server IPv4 address in example configuration

- upcloud/resource_upcloud_firewall_rule.go
Previously firewall rule deletion referenced rules by server ID, which is why firewall rules could not be deleted. This PR fixes it.
> Fix firewall rule deletion

- upcloud/resource_upcloud_firewall_rule.go
As mentioned in #32, the `position` argument in firewall rules is required, it is though, in the schema, set to optional.
This PR changes it to Required.
> Changed position in firewall rule to Required instead of Optional.

- examples/01_server.tf
- upcloud/resource_upcloud_server.go
https://github.com/UpCloudLtd/terraform-provider-upcloud/issues/30
The way the API is set up the storage has to be cloned during the server creation and backup rules added after server creation.
Before this fix the storage was created before the server and thus certain necessary operations were not executed on the main storage which caused the bug of a server without template.
> Bugfix storage backup rule on server creation

- upcloud/resource_upcloud_tag.go
Due to the definition of `Servers` in the `Upcloud.Tag` struct in `upcloud-go-api` the API expects a `Servers` parameter with a string list. This is not totally compatible with the API documentation which expects a map with a key named `server` and a value which consist of a `[]string` of IDs.  
This PR makes the terraform API use a list directly on the `servers` key to match the `upcloud-go-api` structure.
To define a set of tags the following is sufficient with this PR:
```hcl
resource "upcloud_tag" "My-tag" {
name        = "TagName"
description = "TagDescription"
servers     = [
"server-id-1",
"server-id-2"
]
}
```
This should fix #31, although it does not match the http API docs.
> Fix for tags.

- upcloud/resource_upcloud_server.go
This provides a default connection block, removing the need to define one manually in each config.
> Create default connection info for provisioner (refs #45).

- upcloud/resource_upcloud_server.go
I've set the timeout higher to accommodate the longer creation times in Chicago and Singapore.
Also, When creating it is probably better to have it take longer than to retry it a few times..
> Higher timeout for creating servers

- upcloud/resource_upcloud_server.go
getOk requires non-zero value. `False` is the zero value for booleans.
For ref, see #86 
source_ip_filtering
> Fix falses not being set correctly

- upcloud/resource_upcloud_firewall_rules.go
firewall rules cannot be modified when the server is in `maintenance` state
> fix: setting firewall rules

- upcloud/resource_upcloud_server.go
- website/docs/r/upcloud_server.html.markdown
Updated the Terraform provider the provide the ability to enable or disable the per-instance metadata service.
> Expose the ability to explicitly enable or disable metadata service.

- upcloud/resource_upcloud_server.go
allows us to determine the state the server should be after applying changes
e.g. initially stopped server should be stopped after applying terraform config. (currently is not)
> feature: return initial server state from verifyServerStopped/Stated

- upcloud/resource_upcloud_server.go
- upcloud/resource_upcloud_storage.go
- vendor/github.com/UpCloudLtd/upcloud-go-api/upcloud/server.go
Fixes issues that came up when testing
- Running Terraform with the config from the documentation => Pass
- Running a server with single storage resource (without "count" value) => Pass
- Running a server with multiple single resources (without "count" value)=> Pass
- Running a server with storage resources list ("count" value)=> Pass
- Running a server with multiple storage resources lust ("count" value) => Pass
- Resizing a server template storage => Pass
- Test doing changes from control panel like changing server's hostname and was detected in Terraform => Pass
- Resizing/Deleting storage resources:
- Not attached to a server => Pass
- Attached to a server => Fail with: Error: The operation is not allowed while the server 0003f7cc-b697-44fc-9839-50b9a1941e2a is in state 'started'. …
> WIP: Fix/server storage deletion

- website/docs/d/upcloud_zone.html.markdown
- website/docs/d/upcloud_zones.html.markdown
This PR:
- adds docs for the "id" attribute of the zone & zones resources
- does some tidying up :)
> Add missing zone attribute docs

- website/docs/r/upcloud_storage.html.markdown
This PR adds an example of attaching a storage device to a server. The example is in the storage resource docs.
(this PR also removes some unnecessary whitespace)
> Add example of attaching a storage device to a server

- README.md
This PR adds an example of using the env vars in the README's Docker example.
> Add env vars to the Docker example in README

- GNUmakefile
- README.md
- Changes the old `build` target to `build_0_12` and the old `build_0_13` to `build`
- Changes `make` to trigger the 0.13+ build process
- Fixes makefile to grab the version number from git tags, rather than hardcoded `0.1.0`
- Updates the very first example to work out of the box
> Chore: prioritize 0.13+ over 0.12 in documentation and makefile

- upcloud/resource_upcloud_router.go
Previously, the initialization created a slice with len,cap=len(attachednetworks) filled with default values (eg. "" for strings).
After appending to the list, the list then had extra empty entries in the beginning ["", "uuid"] which were returned to TF. 
This is now fixed.
> fix(resource/router): fix creation of attachedNetworks for routers

- README.md
Removes the version-attribute as it breaks things in 0.12, and adds link to the 0.12 build-section to make it clearer that it needs to be built separately for 0.12.
> Improve Terraform 0.12 example

- go.mod
- go.sum
- upcloud/resource_upcloud_network.go
- upcloud/resource_upcloud_router.go
- upcloud/resource_upcloud_router_test.go
- vendor/github.com/UpCloudLtd/upcloud-go-api/internal/globals.go
- vendor/github.com/UpCloudLtd/upcloud-go-api/upcloud/request/network.go
- vendor/github.com/UpCloudLtd/upcloud-go-api/upcloud/service/network.go
- vendor/modules.txt
- pulls in go-api 4.0.0, allowing fot detaching to work
- implement the new go-api detachment methods
- make sure routers are detached when deleting
Fixes #137
> fix(router): allow detaching router and deleting attached routers

- internal/server/server.go
- internal/utils/utils.go
- upcloud/resource_upcloud_server.go
- upcloud/resource_upcloud_server_test.go
Add tags attribute in server resource.
Since the API/SDK don't allow managing tags from /server resource, we need to use /tag resource. Basically on any creation/update we handle the tags separately then we add/remove them from server resource
> feat(server): add tags attribute

- CHANGELOG.md
This PR:
- changes the "Unreleased"-link to point to stuff released after v2.1.0
- changes the 2.1.0-link to point to comparison of changes between 2.0.0 and v2.1.0
- removes the "v" from 2.1.0 header so it matches other headers
> Fix CHANGELOG links for v2.1.0 release

- release/Dockerfile
> chore(ci): bump go version to support darwin arm64

- GNUmakefile
- README.md
- fix the path being generated by `make build` (the version is supposed to be e.g. "2.1.1" but it was "v2.1.1" or "v2.1.1-dirty")
- add extra help to README
> Fixes for local dev

- upcloud/resource_upcloud_network_test.go
- upcloud/resource_upcloud_router_test.go
Remove parallelism for router related test because the API not stable for that endpoint and concurrent creation may end up with a 500.
> fix(tests): disable parallelism for router tests

- upcloud/resource_upcloud_server.go
- upcloud/resource_upcloud_server_test.go
Given a server without tags, the SDK returns an empty array tag for that server. Terraform local state is that case is a nil tag array. So trying a replan will show a diff between the returned SDK values and the local state.
That patch considers an empty tag array as nil.
> fix(server): prevent empty tags from replanning

- upcloud/resource_upcloud_server.go
- upcloud/resource_upcloud_server_test.go
Longer titles are now supported by API.
refactor(server): rename cloudServerTitleLength to serverTitleLength and cloudServerDefaultTitleFromHostname to serverDefaultTitleFromHostname
> feat(server): increase title length from 64 to 255

- CHANGELOG.md
- README.md
- main.go
Start debug server if debug command-line flag is set.
Official documentations:  
https://www.terraform.io/docs/extend/debugging.html#enabling-debugging-in-a-provider
VS Code launch.json example:
```
{
"version": "0.2.0",
"configurations": [
{
"name": "UpCloud provider",
"type": "go",
"request": "launch",
"mode": "auto",
"program": "${workspaceRoot}",
"envFile": "${env:HOME}/terraform/.env",
"args": [
"--debug",
]
}
]
}
```
`envFile` is a file containing your UpCloud credentials.
If UpCloud source is set to `registry.upcloud.com/upcloud/upcloud` in configs then overwrite default provider address in args list:
```
"args": [
"--debug",
"--debug-provider-addr=registry.upcloud.com/upcloud/upcloud",
]
```
> feat(main): add support for debuggers like Delve

- CHANGELOG.md
- upcloud/resource_upcloud_firewall_rules.go
- upcloud/resource_upcloud_firewall_rules_test.go
Remove proto field's default value "tcp" as this prevents settings optional fields value to null and update validator to accept empty string which corresponds to any protocol.
> fix(firewall): Remove proto field's default value "tcp"

- upcloud/resource_upcloud_objectstorage_test.go
Fixes an issue where acceptance tests were failing due `OBJECT_STORAGE_EXISTS` due to non-unique storage object name. Acceptance tests will autogenerate the storage object names with a common prefix. This prefix is also read by the [sweeper](https://www.terraform.io/plugin/sdkv2/testing/acceptance-tests/sweepers).
While modifying the file also changed some of the test related variables to be more descriptive.
> Use unique storage object names in acceptance tests

- upcloud/resource_upcloud_objectstorage.go
- upcloud/resource_upcloud_objectstorage_test.go
Currently buckets are created in the order of configuration. However they are stored in the order what the UpCloud API returns. Since users should be able to change the order of the configuration, and the resources are not dependent on each other, we should store the buckets into sets instead of lists.
Fixes issue #181.
> Use set instead of list for storing buckets in state

- CHANGELOG.md
Currently changelog entries are missing release dates. This PR adds release dates of previous releases. Uses ISO 8601 date format.
> Add release dates to changelog entries

- CHANGELOG.md
- go.mod
- go.sum
- upcloud/provider.go
- upcloud/resource_upcloud_server.go
Return more descriptive error message if subaccount tries to
edit server tags.
Update Go API dependency from v4.1.2 to v4.1.3 to get access to
new account functions.
> fix(server): subaccount tagging error handling

- .goreleaser.yml
- CHANGELOG.md
Build-time variable injection was modified on #164 and #165 where the variable was moved from `globals` package to `config`. Since then the release pipeline has still been referencing the old package. Due to this configuration issue the version information has not made it into the release builds. API client uses this information for initialising the HTTP user agent correctly.
> Fix build-time variable injection for release builds

- CHANGELOG.md
- upcloud/resource_upcloud_server.go
Fix missing template id if resource creation fails on tag errors.
Missing id will prevent deleting the resource.
> fix(server): missing template id

- upcloud/resource_upcloud_storage_test.go
This PR just combines a few storage acceptance tests into one. Those tests actually just tested different schema properties and updated to them, so it's better to combine them into one to save some time.
I also removed the function that creates config string and replaced it with actual string. While this might not be fully dry, IMO it's easier to just eyball the config as you write the checks for said config. Having to scroll few hundreds line down to check what is in the actual config is imo annoying
> refactor(storage): combine multiple acceptance tests into one

- docs/resources/loadbalancer_frontend_rule.md
- docs/resources/loadbalancer_resolver.md
- go.mod
- go.sum
- internal/service/loadbalancer/resolver.go
Update to go SDK 4.4.2
Fixed resolver spelling (related to SDK update)
Update docs (because we missed some updates in one of the past additions)
> Chore/update go sdk 4.4.2

- CHANGELOG.md
- DEVELOPING.md
- internal/server/server.go
- upcloud/resource_upcloud_server.go
- upcloud/resource_upcloud_server_test.go
- Ignore the order of tags in server tests: If tags are already defined by other servers, they might appear in different order than the one specified in tag server API request.
- Remove all tags when tags change into an empty value.
- Delete unused tags created with server resource on server delete 
- Improve tag handling on server create, update, and delete:
- Remove extra TagServer call.
- Return and print warning if trying to create existing tag with different letter casing. After this, we should not get TAG_EXISTS errros, which previously resulted to incorrect tags state.
- Only add and delete tags if necessary on server update.
- Validate that tags do no contain duplicates and supress diff when only order of the tags changes
> Refactor server tags handling

- CHANGELOG.md
- DEVELOPING.md
- go.mod
- go.sum
Update `upcloud-go-api` to version v4.5.0.
> chore(lib): update UpCloud Go API client library

- docs/resources/server.md
- internal/service/server/server.go
I had to check source code for possible values for password_delivery property. These could be added to documentation.
> Adds password delivery methods to documentation

- .github/workflows/docs.yml
- DEVELOPING.md
Testing results (1st commit):
- See #289 for test PR that adds extra text to `docs/` that will be removed as it is not found from templates or source-code.
- See #290 for PR created by this new action. (Edited PR body manually to test if GitHub changes Commit ID automatically into a link)
Testing result (2nd commit):
- #292
- #293
> Add action for auto-generating docs

- CHANGELOG.md
- internal/service/database/database.go
As of DBaaS 1.2.0 all properties are in snake case.
> fix(dbaas): remove special handling of dots in postgres properties

- CHANGELOG.md
- upcloud/provider.go
This does not change how these inputs are used: providing these values in the provider block has already been optional if credentials were defined as environment variables.
> fix: set credentials as optional inputs

- .github/workflows/terraform.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
This allows us to limit the Terraform acceptance tests to 1 concurrent workflow at a time.
> ci(terraform): concurrency group for workflow

- GNUmakefile
Fixes a `GNUmakefile` issue when using go workspace and multiple modules are stored in `${MODULE}`.
Before:
```shell
make
==> Checking that code complies with gofmt requirements...
go build \
-tags release \
-ldflags '-X github.com/UpCloudLtd/progress github.com/UpCloudLtd/terraform-provider-upcloud github.com/UpCloudLtd/terraform-provider-upcloud/tools github.com/UpCloudLtd/upcloud-cli github.com/UpCloudLtd/upcloud-go-api/v4/internal/config.Version=v2.5.0-24-g44a59373-dirty' \
-o ~/.terraform.d/plugins/registry.upcloud.com/upcloud/upcloud/2.5.0/linux_amd64/terraform-provider-upcloud_v2.5.0
/usr/lib/go-1.18/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value
make: *** [GNUmakefile:22: build] Error 2
```
After:
```
make
==> Checking that code complies …
```
> fix(makefile): list current package in workspace

- CHANGELOG.md
This new release only fixes docs displayed in TF registry to make a note of all kubernetes resources being in alpha
> chore: prepare 2.6.1 release

- docs/resources/server.md
- internal/service/server/server.go
This PR adds examples on how to list available public and private templates.
> docs(server): add `upctl` command for listing templates

- CHANGELOG.md
- internal/service/gateway/gateway.go
This allows using `depends_on` to wait for gateway to be running if there are servers or other resources that need internet connection through the gateway right after creation (e.g. servers user-data script needs access to internet).
> fix(gateway): wait for running state when creating the gateway

- .pre-commit-config.yaml
- CHANGELOG.md
- docs/resources/kubernetes_cluster.md
- go.mod
- go.sum
- internal/service/kubernetes/kubernetes.go
- new `plan` field to `upcloud_kubernetes_cluster` resource
- update golangci-lint to v1.52.2
- update upcloud-go-api to v6.1.0
> feat(kubernetes): new `plan` field to cluster resource

- internal/service/kubernetes/data_sources.go
- internal/service/kubernetes/kubernetes.go
- internal/service/kubernetes/node_group.go
Update documentation for Managed Kubernetes related resources and datasources:
Resources affected:
- `upcloud_kubernetes_cluster`
- `upcloud_kubernetes_node_group`
Data sources affected:
- `upcloud_kubernetes_cluster`
No longer experimental.
> chore(docs): update docs for k8s resources

- internal/service/database/database_common.go
- internal/service/kubernetes/kubernetes.go
- internal/service/kubernetes/node_group.go
Align help text on how different resources handle `plan` and `zone` attributes.
> chore(docs): add help text to list db and k8s plans

- upcloud/resource_upcloud_kubernetes_test.go
- upcloud/testdata/upcloud_kubernetes/kubernetes_s1.tf
- upcloud/testdata/upcloud_kubernetes/kubernetes_s2.tf
Enable k8s acceptance tests by default and remove env variable check.
Added `ignore_changes` workaround for `upcloud_network` for both the tests. Detailed explanation in [uks-instructions/KNOWN_ISSUES.md](https://github.com/UpCloudLtd/uks-instructions/blob/5e18ad55ee636606560b89439038f41c33464e5b/KNOWN_ISSUES.md#terraform).
> chore(test): enable k8s acceptance tests by default

- CHANGELOG.md
- internal/service/server/server.go
Add support for `timezone`,  `nic_model` and `video_model` attributes in `server` resource.
Fixes #206
> chore(server): additional fields to server

- upcloud/testdata/upcloud_managed_database/redis_properties_s1.tf
- upcloud/testdata/upcloud_managed_database/redis_properties_s2.tf
Helps janitor work in case of dangling resources after failed runs :)
> chore(test): align Redis properties test with the rest

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/terraform.yml
- .golangci.yml
- go.mod
- Use Go 1.20 in `go.mod` and CI actions
- Remove deprecated linters
> chore: use Go 1.20

- CHANGELOG.md
- internal/service/kubernetes/node_group.go
Remove node group size validation from the provider and rely on API instead. This is a leftover from earlier test phases.
> chore(kubernetes): remove node group size validation

- go.mod
- go.sum
Skip [upgrading to 1.57.1](https://github.com/UpCloudLtd/terraform-provider-upcloud/pull/429) as it introduced new [bug](https://github.com/grpc/grpc-go/releases/tag/v1.57.2) .
> chore(deps): bump google.golang.org/grpc from 1.57.0 to 1.57.2

- upcloud/provider.go
- upcloud/resource_upcloud_objectstorage_test.go
Hello Team,
I've encountered a recurring issue while deploying infrastructure using Terraform with the UpCloud provider. Specifically, I often receive a timeout error from my Atlantis pipeline, despite the virtual machine (VM) configurations being applied as expected but it's cause the pipeline is detected as failed. This issue seems to be related to the client timeout settings in the UpCloud Terraform provider.
**Error Encountered:**
```bash
Error: Post "https://api.upcloud.com/1.3/server/xxxxxx-xxxxx-4807-b1d4-9e9d944470cf/start": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
with upcloud_server.dbxxxx_managed_by_terraform,
on database.tf line 8, in resource "upcloud_server" "dbxxxx_managed_by_terraform":
8: resource "upcloud_server" …
```
> Enhance Timeout Configuration for UpCloud Provider in Terraform

- CHANGELOG.md
> chore: prepare release v5.1.0

- CHANGELOG.md
- docs/resources/router.md
- internal/service/network/network.go
- internal/service/networkpeering/networkpeering.go
- internal/service/router/router.go
- internal/utils/error.go
- upcloud/provider.go
- upcloud/sdkv2_provider.go
Also fixes error handling in `Read` functions of `upcloud_network` and `upcloud_network_peering` so that these resources are removed from state, if API returns 404 response.
> feat(router): add `labels` support, re-implement with plugin framework

- .github/workflows/docs.yml
- .github/workflows/generate.yml
- .gitignore
- internal/service/database/properties/generate_types_data.sh
Also updates the DB properties generate script so that differences are presented in human readable format.
> ci: add workflow to automatically run `make generate`

- .github/workflows/generate.yml
This avoids creating two separate bot pull requests about the same change.
> feat: update docs in the generate workflow

- CHANGELOG.md
- internal/service/storage/storage.go
- upcloud/resource_upcloud_storage_test.go
Ref https://developers.upcloud.com/1.3/9-storages/
> fix(storage): sync title length constraint with API

- CHANGELOG.md
- internal/service/router/router.go
- upcloud/resource_upcloud_router_test.go
- upcloud/testdata/upcloud_router/delete_attached_s1.tf
- upcloud/testdata/upcloud_router/delete_attached_s2.tf
- upcloud/testdata/upcloud_router/detach_s1.tf
- upcloud/testdata/upcloud_router/detach_s2.tf
- upcloud/testdata/upcloud_router/static_routes_s1.tf
- upcloud/testdata/upcloud_router/static_routes_s2.tf
Also fixes `attached_networks` order, removes unwanted empty string from `attached_networks`, and removes service
routes from `static_route` set.
> feat(router): add `static_routes` set for listing all routes

- CHANGELOG.md
- internal/service/loadbalancer/frontend.go
- internal/service/managedobjectstorage/policies_data_source.go
- internal/service/managedobjectstorage/policy.go
- upcloud/provider.go
- upcloud/resource_upcloud_managed_object_storage_user_test.go
- upcloud/sdkv2_provider.go
- upcloud/testdata/upcloud_managed_object_storage/managed_object_storage_user_s1.tf
- upcloud/testdata/upcloud_managed_object_storage/managed_object_storage_user_s2.tf
Also migrates `upcloud_managed_object_storage_policy` to Terraform plugin framework.
> fix(objsto): ignore whitespace and extra escapes in policy document

- release/Dockerfile
To match the version defined in `go.mod`, set `GO_VERSION` in `Dockerfile` to 1.22.
> ci(release): bump go to 1.22 in Dockerfile

- CHANGELOG.md
> chore: prepare release v5.15.0

- CHANGELOG.md
- internal/service/server/create_request.go
- internal/service/server/interfaces.go
- internal/service/server/server.go
- internal/service/server/server_test.go
- internal/service/server/storages.go
- internal/service/server/tags.go
- internal/service/server/utils.go
- internal/service/server/validators.go
- internal/service/storage/backup_rule.go
- internal/service/storage/storage.go
- internal/utils/default.go
- internal/utils/server.go
- internal/utils/types.go
- internal/validator/domainname.go
- upcloud/provider.go
- upcloud/resource_upcloud_server_group_test.go
- upcloud/resource_upcloud_server_test.go
- upcloud/sdkv2_provider.go
- upcloud/testdata/upcloud_server/server_ifaces_s3.tf
Also makes server template storage tier configurable (#536) and sets interface IP addresses as unknown (known after apply) in planning (#646).
> refactor(server): migrate server resource to plugin framework

- internal/service/firewall/firewall.go
Add a description for possible action, Default action values either "Accept" or "Drop"
> docs: update firewall_rule action description

- CHANGELOG.md
- internal/service/kubernetes/cluster.go
- internal/service/kubernetes/kubernetes.go
- internal/service/kubernetes/node_group.go
- upcloud/resource_upcloud_kubernetes_test.go
The back-end side has been updated so that cluster does not return HTTP 404 response until it has been fully removed. Also remove client side default value for plan and use default value defined by API instead.
> fix(kubernetes): remove extra waits from cluster and node-group delete

- CHANGELOG.md
- internal/service/server/server.go
- internal/service/server/server_test.go
- internal/service/server/utils.go
- upcloud/resource_upcloud_server_test.go
Add support for resizing server plans without requiring a reboot using the new `hot_resize` attribute. When enabled, this feature attempts to change the server plan without stopping the server. If hot resize fails, the apply operation will fail with a clear error message.
Key changes:
- Add `hot_resize` attribute to the server resource schema
- Implement logic to detect when server restart is required
- Update server modification code to attempt hot resize when applicable
- Add comprehensive tests for various hot resize scenarios
- Improve error handling to provide clear guidance when hot resize fails
This feature provides users with a way to change server plans with zero downtime when the hot resize feature is available. If the hot resize operation fails, users can set `hot_resize = …
> feat(server): implement hot resize

- CHANGELOG.md
- internal/service/server/server.go
The Update method was incorrectly attempting to load the Terraform configuration into the state variable instead of the config variable.
Consequently, further in the method this call has previously received an empty Host value:
```
server, err := utils.VerifyServerStarted(ctx, request.StartServerRequest{UUID: uuid, Host: int(config.Host.ValueInt64())}, r.client)
```
> fix(server): config loading in Update

- CHANGELOG.md
- examples/resources/upcloud_storage_backup/resource.tf
- internal/service/storage/storage_backup.go
- subcategories.json
- upcloud/provider.go
- upcloud/resource_upcloud_storage_test.go
- upcloud/testdata/upcloud_kubernetes/kubernetes_storage_encryption_s1.tf
- upcloud/testdata/upcloud_kubernetes/kubernetes_storage_encryption_s2.tf
- Added new storage backup resource: upcloud_storage_backup
- Added TestAccUpCloudStorageBackup_basic test
- Example:
```shell
resource "upcloud_storage_backup" "backup"{
title = "backup13"
source_storage = "0185b32e-41fd-46e4-b32e-a9d9028eaec6"
}
``` 
Notes: The resource manages one backup. Updates only changes the title. Deleting the resource from the configuration will delete the managed backup
> feat(storage backup): Implementation of upcloud_storage_backup

- CHANGELOG.md
- go.mod
- go.sum
- internal/service/server/interface_test.go
- internal/service/server/interfaces.go
- upcloud/resource_upcloud_server_network_test.go
- upcloud/testdata/upcloud_server/server_ifaces_s2.tf
> fix(server): assign and delete addresses on `additional_ip_address` changes
